Create tempdir + parses makefile

diff --git a/maque b/maque
--- a/maque
+++ b/maque
@@ -5,6 +5,7 @@ OPTS_MAKEFILE=`find . -name [Mm]akefile -maxdepth 1`
 OPTS_DRYRUN=false
 OPTS_KEEPGOING=false
 
+# Show usage
 usage () {
     cat <<EOL
 Usage: $(basename $0) [-f makefile] [-hkn] [target]
@@ -16,6 +17,16 @@ Options:
 EOL
 }
 
+# Create tempdir
+init_tmpdir () {
+    # Uses TMPDIR (fallback: /tmp)
+    # ex: /tmp/maque-1234
+    TDIR=${TMPDIR:-/tmp/}$(basename $0)-$$
+    mkdir -p $TDIR
+    trap "rm -r $TDIR" EXIT
+}
+
+# Parse commandline options
 parse_commandline () {
     while getopts ":f:kn" ARG; do
         case "$ARG" in
@@ -35,23 +46,51 @@ parse_commandline () {
         esac
     done
 
+    # Testing makefile existence
     if [ ! -f $OPTS_MAKEFILE ]; then
         echo "Makefile not found"
-        usage
+        usage >&2
         exit 1
     fi
 
 }
 
+# Parse makefile
+parse_makefile () {
+    CURRENT_TARGET=""
+
+    # Remove comments, trailing whitespaces and empty lines
+    # TODO: Use var instead of file
+    cat $1 | sed -e 's/#.*$//g' -e 's/[[:space:]]*$//' | grep -ve '^[[:space:]]*$' > $TDIR/makefile
+
+    # Keep leading spaces/tabs in `read`
+    OLDIFS=$IFS
+    IFS=''
+
+    while read LINE; do
+        if [ ! -z $CURRENT_TARGET ] && (echo "$LINE" | grep -q ^'\t'); then
+            # Append commands to $CURRENT_TARGET commands file
+            echo "$LINE" | sed 's/^[[:space:]]*\(.*\)$/\1/' >> $TDIR/$CURRENT_TARGET/commands
+        elif (echo "$LINE" | grep -q '^[A-Za-z.]\+:\( [A-Za-z.]\+\)*$'); then
+            # Change $CURRENT_TARGET and add dependencies in file
+            CURRENT_TARGET=`echo $LINE | cut -d ':' -f 1`
+            mkdir $TDIR/$CURRENT_TARGET
+            touch $TDIR/$CURRENT_TARGET/commands
+            echo "$LINE" | sed 's/^[A-Za-z.]*: *//g' > $TDIR/$CURRENT_TARGET/dependencies
+        else
+            # TODO: More explicit error
+            echo "Error while parsing Makefile" >&2
+            exit 2
+        fi
+    done < $TDIR/makefile
+
+    # Restore IFS
+    IFS=$OLDIFS
+}
+
+# Run everything
+init_tmpdir
 parse_commandline $*
-
-echo "Running with options:
-Makefile: $OPTS_MAKEFILE
-Dry-run: $OPTS_DRYRUN
-Keep going: $OPTS_KEEPGOING"
-
-if $OPTS_DRYRUN; then
-    echo "Dry-run";
-fi
+parse_makefile $OPTS_MAKEFILE
 
 # vim: ts=4:sw=4:et
